[build]
  command = "npm run build"
  publish = "dist" # <- foarte important, pentru Vite

[build.processing]
  skip_processing = false

[build.cache]
  paths = []

[build.environment]
  NODE_VERSION = "18"
  VITE_API_URL = "https://oltenitaimobiliare-backend.onrender.com/api"
  CI = "false"
  NETLIFY_USE_YARN = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
